services:

  synapse:
    image: docker.io/matrixdotorg/synapse:latest
    container_name: synapse
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    volumes:
      - /var/synapse/data:/data
    depends_on:
      - db
    ports:
      - 8008:8008/tcp
    networks:
      - synapse_network

  db:
    image: docker.io/postgres:17-alpine
    container_name: synapse-postgres
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    expose:
      - 5432
    volumes:
      - /var/synapse/postgresql/data:/var/lib/postgresql/data
    networks:
      - synapse_network

  redis:
    image: redis:latest
    container_name: synapse-redis
    restart: unless-stopped
    networks:
      - synapse_network

  synapse-admin:
    container_name: synapse-admin
    image: awesometechnologies/synapse-admin:latest
    restart: unless-stopped
    ports:
      - "8010:80"
    networks:
      - synapse_network

  turnserver:
    container_name: synapse-turnserver
    image: instrumentisto/coturn
    restart: unless-stopped
    ports:
      - "3488:3478/udp"
      - "3488:3478/tcp"
      - "5359:5349/tcp"
    environment:
      - TURNSERVER_LISTEN_PORT=3478
      - TURNSERVER_ALT_LISTEN_PORT=5349
      - TURNSERVER_MIN_PORT=49152
      - TURNSERVER_MAX_PORT=65535
      - TURNSERVER_REALM=matrix.domen.com
      - TURNSERVER_STATIC_AUTH_SECRET=secret
    volumes:
      - /var/synapse/turn:/etc/coturn
    networks:
      - synapse_network

  auth-service:
    image: ghcr.io/element-hq/lk-jwt-service:latest
    container_name: element-call-jwt
    hostname: auth-server
    environment:
      - LK_JWT_PORT=8080
      - LIVEKIT_URL=https://voice.domen.com/livekit/sfu
      - LIVEKIT_KEY=devkey
      - LIVEKIT_SECRET=secret
      - LIVEKIT_LOCAL_HOMESERVERS=matrix.domen.com
    restart: unless-stopped
    ports:
      - 8075:8080
    networks:
      - synapse_network

  livekit:
    image: livekit/livekit-server:latest
    container_name: element-call-livekit
    command: --config /etc/livekit.yaml
    ports:
      - 7880:7880/tcp
      - 7881:7881/tcp
      - 50100-50200:50100-50200/udp
    restart: unless-stopped
    volumes:
      - /var/synapse/livekit/config.yaml:/etc/livekit.yaml:ro
    networks:
      - synapse_network

networks:
  synapse_network:
